import numpy as np
dataset = np.random.randint(0,100,size=(120,5))
print(dataset.shape)
print(dataset)
new_data = dataset.reshape(60,10)
print(new_data.shape)
print(new_data)
sum=np.sum(new_data)
print(sum)
row_wise_sum=np.sum(new_data,axis=1)
rws=np.array(row_wise_sum)
print(row_wise_sum)
column_wise_sum=np.sum(new_data,axis=0)
print(column_wise_sum)
new=new_data[new_data>80]
count=np.size(new)
print(new,count)
row = rws.reshape(60,1)
new_result= np.concatenate((new_data,row), axis=1)
print(new_result)